---
env:
  - GO111MODULE=on
  - CGO_ENABLED=0
before:
  hooks:
    - go mod download

builds:
  - id: captain-hook-linux
    main: ./cmd/captain-hook/captain-hook.go
    binary: captain-hook
    ldflags:
      - -X github.com/jenkins-infra/captain-hook/pkg/version.Version={{.Version}} -X github.com/jenkins-infra/captain-hook/pkg/version.Revision={{.ShortCommit}} -X github.com/jenkins-infra/captain-hook/pkg/version.BuildDate={{.CommitDate}} -X github.com/jenkins-infra/captain-hook/pkg/version.BuiltBy=goreleaser
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - s390x
      - ppc64le

  - id: captain-hook-darwin
    main: ./cmd/captain-hook/captain-hook.go
    binary: captain-hook
    ldflags:
      - -X github.com/jenkins-infra/captain-hook/pkg/version.Version={{.Version}} -X github.com/jenkins-infra/captain-hook/pkg/version.Revision={{.ShortCommit}} -X github.com/jenkins-infra/captain-hook/pkg/version.BuildDate={{.CommitDate}} -X github.com/jenkins-infra/captain-hook/pkg/version.BuiltBy=goreleaser
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "{{ .ProjectName }}-checksums.txt"
  algorithm: sha256

changelog:
  skip: false

release:
  draft: false
  prerelease: false
  name_template: "{{.Tag}}"
