/*
 Generated Code
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// HookListerExpansion allows custom methods to be added to
// HookLister.
type HookListerExpansion interface{}

// HookNamespaceListerExpansion allows custom methods to be added to
// HookNamespaceLister.
type HookNamespaceListerExpansion interface{}
