/*
 Generated Code
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	captainhookiov1alpha1 "github.com/jenkins-infra/captain-hook/pkg/api/captainhookio/v1alpha1"
	versioned "github.com/jenkins-infra/captain-hook/pkg/client/clientset/versioned"
	internalinterfaces "github.com/jenkins-infra/captain-hook/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/jenkins-infra/captain-hook/pkg/client/listers/captainhookio/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// HookInformer provides access to a shared informer and lister for
// Hooks.
type HookInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.HookLister
}

type hookInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewHookInformer constructs a new informer for Hook type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewHookInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredHookInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredHookInformer constructs a new informer for Hook type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredHookInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CaptainhookV1alpha1().Hooks(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CaptainhookV1alpha1().Hooks(namespace).Watch(context.TODO(), options)
			},
		},
		&captainhookiov1alpha1.Hook{},
		resyncPeriod,
		indexers,
	)
}

func (f *hookInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredHookInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *hookInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&captainhookiov1alpha1.Hook{}, f.defaultInformer)
}

func (f *hookInformer) Lister() v1alpha1.HookLister {
	return v1alpha1.NewHookLister(f.Informer().GetIndexer())
}
