# Default values for captain-hook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Number of replicas to run
replicaCount: 1

image:
  repository: jenkinsciinfra/captain-hook
  pullPolicy: IfNotPresent
  # -- Overrides the image tag whose default is the chart appVersion.
  tag: ""

# -- Path to listen for webhook events on
hookPath: /hook
# -- Url to send all webhook events to
forwardURL: http://jenkins:8080/github-webhook/
# -- Should we relay to insecure tls endpoints
insecureRelay: false
# -- Maximum age in seconds a successful webhook should be live for
maxAgeInSeconds: 3600
# -- Number of seconds the next retry should not be attempted before
attemptRetryAfterInSeconds: 60
# -- Maximum number of times this webhook should be attempted
maxAttempts: 10

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- The name of the service account to use. If not set and create is true, a name is generated using the fullname template
  name: ""

service:
  type: ClusterIP
  port: 8080

ingress:
  # -- Create an ingress resource for this service
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - paths:
        - backend:
            service:
              name: captain-hook
              port:
                number: 8080

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# -- Autoscaling configuration, disabled by default
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
